/**
 * test-api.js
 *
 * Integration test suite for the Transaction Categorization API.
 * Runs against a live dev server on localhost:3000.
 *
 * Keys are read from .env.test, which is generated by setup-test-key.js.
 * Never hardcode API keys in this file.
 *
 * Usage:
 *   node test-api.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── Load .env.test ───────────────────────────────────────────────────────────

const envPath = path.resolve(__dirname, '.env.test');
if (!fs.existsSync(envPath)) {
  console.error('✗ .env.test not found. Run: node setup-test-key.js');
  process.exit(1);
}

const envVars = {};
for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq === -1) continue;
  envVars[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
}

const TEST_KEY_ACTIVE    = envVars['TEST_KEY_ACTIVE'];
const TEST_KEY_INACTIVE  = envVars['TEST_KEY_INACTIVE'];
const TEST_KEY_EXHAUSTED = envVars['TEST_KEY_EXHAUSTED'];

if (!TEST_KEY_ACTIVE || !TEST_KEY_INACTIVE || !TEST_KEY_EXHAUSTED) {
  console.error('✗ .env.test is missing required keys. Re-run: node setup-test-key.js');
  process.exit(1);
}

// ─── Config ───────────────────────────────────────────────────────────────────

const API_URL = process.env.API_URL || 'http://localhost:3000/api/v1/categorize';

const colors = {
  reset:  '\x1b[0m',
  green:  '\x1b[32m',
  red:    '\x1b[31m',
  yellow: '\x1b[33m',
  blue:   '\x1b[34m',
  dim:    '\x1b[2m',
};

// ─── Test runner ──────────────────────────────────────────────────────────────

let passCount = 0;
let failCount = 0;
const failures = [];

function log(msg, color = colors.reset) {
  console.log(`${color}${msg}${colors.reset}`);
}

function section(title) {
  log(`\n${title}`, colors.yellow);
}

async function test(name, fn) {
  try {
    await fn();
    passCount++;
    log(`  ✓ ${name}`, colors.green);
  } catch (err) {
    failCount++;
    failures.push({ name, message: err.message });
    log(`  ✗ ${name}`, colors.red);
    log(`    ${err.message}`, colors.dim);
  }
}

// ─── HTTP helpers ─────────────────────────────────────────────────────────────

/**
 * Standard JSON call — body is serialised automatically.
 */
async function call({ key, body }) {
  const headers = { 'Content-Type': 'application/json' };
  if (key !== undefined) headers['x-api-key'] = key;

  const res = await fetch(API_URL, {
    method: 'POST',
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  return { res, data };
}

/**
 * Sends a raw string body so we can test malformed JSON without JSON.stringify
 * sanitising it first.
 */
async function callRaw({ key, rawBody }) {
  const headers = { 'Content-Type': 'application/json' };
  if (key) headers['x-api-key'] = key;

  const res = await fetch(API_URL, {
    method: 'POST',
    headers,
    body: rawBody,
  });
  const data = await res.json();
  return { res, data };
}

function assert(condition, message) {
  if (!condition) throw new Error(message || 'Assertion failed');
}

function assertStatus(res, expected) {
  assert(res.status === expected, `Expected HTTP ${expected}, got ${res.status}`);
}

function assertError(data, expected) {
  assert(data.error === expected, `Expected error "${expected}", got "${data.error}"`);
}

function assertResultShape(result, index = 0) {
  const prefix = `result[${index}]`;
  assert(typeof result.original  === 'string',  `${prefix}.original must be a string`);
  assert(typeof result.normalized === 'string', `${prefix}.normalized must be a string`);
  assert(typeof result.merchant  === 'string',  `${prefix}.merchant must be a string`);
  assert(typeof result.category  === 'string',  `${prefix}.category must be a string`);
  assert(
    typeof result.confidence === 'number' &&
      result.confidence >= 0 &&
      result.confidence <= 1,
    `${prefix}.confidence must be a number in [0, 1], got ${result.confidence}`
  );
}

// ─── Test suites ──────────────────────────────────────────────────────────────

async function runPhase1() {
  section('Phase 1: Valid requests');

  await test('Single transaction — response shape', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['AMAZON.COM'] },
    });
    assertStatus(res, 200);
    assert(Array.isArray(data.results), 'results must be an array');
    assert(data.results.length === 1, `Expected 1 result, got ${data.results.length}`);
    assert(data.meta.count === 1, `meta.count should be 1, got ${data.meta.count}`);
    assertResultShape(data.results[0]);
  });

  await test('Multiple transactions — count matches', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['WALMART', 'NETFLIX', 'STARBUCKS'] },
    });
    assertStatus(res, 200);
    assert(data.results.length === 3, `Expected 3 results, got ${data.results.length}`);
    assert(data.meta.count === 3, `meta.count should be 3`);
    data.results.forEach((r, i) => assertResultShape(r, i));
  });

  await test('All fields present on every result', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['SQ *BLUE BOTTLE COFFEE', 'PAYPAL *RANDOM', 'UBER 12345'] },
    });
    assertStatus(res, 200);
    data.results.forEach((r, i) => assertResultShape(r, i));
  });

  await test('Exactly 100 transactions (boundary)', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: Array(100).fill('WALMART SUPERCENTER') },
    });
    assertStatus(res, 200);
    assert(data.results.length === 100, `Expected 100 results, got ${data.results.length}`);
  });

  await test('Duplicate transactions all returned', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['STARBUCKS', 'STARBUCKS', 'STARBUCKS'] },
    });
    assertStatus(res, 200);
    assert(data.results.length === 3, 'Duplicates should each produce a result');
    for (const r of data.results) {
      assert(
        r.merchant.toLowerCase() === 'starbucks',
        `Expected merchant Starbucks, got ${r.merchant}`
      );
    }
  });
}

async function runPhase2() {
  section('Phase 2: Input validation');

  await test('Missing request body → 400 invalid_json', async () => {
    const { res, data } = await call({ key: TEST_KEY_ACTIVE });
    assertStatus(res, 400);
    assertError(data, 'invalid_json');
  });

  await test('Malformed JSON (truncated) → 400 invalid_json', async () => {
    const { res, data } = await callRaw({
      key: TEST_KEY_ACTIVE,
      rawBody: '{"transactions": ["WALMART"',
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_json');
  });

  await test('Malformed JSON (bare string) → 400 invalid_json', async () => {
    const { res, data } = await callRaw({
      key: TEST_KEY_ACTIVE,
      rawBody: 'not json at all',
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_json');
  });

  await test('Body is valid JSON but not an object → 400 invalid_request', async () => {
    const { res, data } = await callRaw({
      key: TEST_KEY_ACTIVE,
      rawBody: '"just a string"',
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_request');
  });

  await test('Missing transactions field → 400 missing_field', async () => {
    const { res, data } = await call({ key: TEST_KEY_ACTIVE, body: {} });
    assertStatus(res, 400);
    assertError(data, 'missing_field');
  });

  await test('Transactions is a string, not array → 400 invalid_type', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: 'not an array' },
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_type');
  });

  await test('Transactions is a number → 400 invalid_type', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: 42 },
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_type');
  });

  await test('Empty array → 400 empty_array', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: [] },
    });
    assertStatus(res, 400);
    assertError(data, 'empty_array');
  });

  await test('101 transactions → 400 array_too_large', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: Array(101).fill('WALMART') },
    });
    assertStatus(res, 400);
    assertError(data, 'array_too_large');
  });

  await test('Non-string item in array → 400 invalid_item_type', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['WALMART', 123, 'NETFLIX'] },
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_item_type');
  });

  await test('Null item in array → 400 invalid_item_type', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: [null] },
    });
    assertStatus(res, 400);
    assertError(data, 'invalid_item_type');
  });

  await test('Whitespace-only string → 400 empty_string', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['   '] },
    });
    assertStatus(res, 400);
    assertError(data, 'empty_string');
  });

  await test('Mixed valid and whitespace-only → 400 empty_string', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['WALMART', '   ', 'NETFLIX'] },
    });
    assertStatus(res, 400);
    assertError(data, 'empty_string');
  });

  await test('String exceeding 200 chars → 400 string_too_long', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['A'.repeat(201)] },
    });
    assertStatus(res, 400);
    assertError(data, 'string_too_long');
  });

  await test('Exactly 200 chars → 200 accepted', async () => {
    const { res } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['A'.repeat(200)] },
    });
    assertStatus(res, 200);
  });
}

async function runPhase3() {
  section('Phase 3: Authentication');

  await test('Missing API key header → 401 missing_api_key', async () => {
    const { res, data } = await call({ body: { transactions: ['WALMART'] } });
    assertStatus(res, 401);
    assertError(data, 'missing_api_key');
  });

  await test('Unknown API key → 403 invalid_api_key', async () => {
    const { res, data } = await call({
      key: 'txcat_thiskeyhasneverbeeninthedb',
      body: { transactions: ['WALMART'] },
    });
    assertStatus(res, 403);
    assertError(data, 'invalid_api_key');
  });

  await test('Inactive API key → 403 invalid_api_key', async () => {
    const { res, data } = await call({
      key: TEST_KEY_INACTIVE,
      body: { transactions: ['WALMART'] },
    });
    assertStatus(res, 403);
    assertError(data, 'invalid_api_key');
  });

  await test('Empty string API key → 401 missing_api_key', async () => {
    const headers = {
      'Content-Type': 'application/json',
      'x-api-key': '',
    };
    const res = await fetch(API_URL, {
      method: 'POST',
      headers,
      body: JSON.stringify({ transactions: ['WALMART'] }),
    });
    const data = await res.json();
    // Empty string header is treated the same as absent
    assert(
      res.status === 401 || res.status === 403,
      `Expected 401 or 403, got ${res.status}`
    );
  });
}

async function runPhase4() {
  section('Phase 4: Quota and limits');

  await test('Monthly quota exceeded → 429 monthly_quota_exceeded', async () => {
    const { res, data } = await call({
      key: TEST_KEY_EXHAUSTED,
      body: { transactions: ['WALMART'] },
    });
    assertStatus(res, 429);
    assertError(data, 'monthly_quota_exceeded');
  });
}

async function runPhase5() {
  section('Phase 5: Merchant recognition');

  await test('Exact-match merchants (Walmart, Netflix, Starbucks)', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: [
          'WALMART SUPERCENTER #1234',
          'NETFLIX.COM',
          'STARBUCKS #56789',
        ],
      },
    });
    assertStatus(res, 200);
    assert(data.results[0].merchant.toLowerCase() === 'walmart',    `Expected Walmart, got ${data.results[0].merchant}`);
    assert(data.results[1].merchant.toLowerCase() === 'netflix',    `Expected Netflix, got ${data.results[1].merchant}`);
    assert(data.results[2].merchant.toLowerCase() === 'starbucks',  `Expected Starbucks, got ${data.results[2].merchant}`);
    assert(data.results[0].category === 'groceries',   `Expected groceries, got ${data.results[0].category}`);
    assert(data.results[1].category === 'entertainment', `Expected entertainment, got ${data.results[1].category}`);
    assert(data.results[2].category === 'food',        `Expected food, got ${data.results[2].category}`);
  });

  await test('Processor prefixes are stripped before matching', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: [
          'PAYPAL *NETFLIX',
          'SQ *STARBUCKS',
          'STRIPE* AMAZON',
        ],
      },
    });
    assertStatus(res, 200);
    assert(data.results[0].merchant.toLowerCase() === 'netflix',   `Prefix not stripped: got ${data.results[0].merchant}`);
    assert(data.results[1].merchant.toLowerCase() === 'starbucks', `Prefix not stripped: got ${data.results[1].merchant}`);
    assert(data.results[2].merchant.toLowerCase() === 'amazon',    `Prefix not stripped: got ${data.results[2].merchant}`);
  });

  await test('Exact-match guard: "shell shocked" does not match Shell', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['SHELL SHOCKED RECORDS'] },
    });
    assertStatus(res, 200);
    assert(
      data.results[0].merchant.toLowerCase() !== 'shell',
      `"shell shocked" should not match Shell merchant, got ${data.results[0].merchant}`
    );
  });

  await test('Exact-match guard: "amazonian" does not match Amazon', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['AMAZONIAN IMPORTS'] },
    });
    assertStatus(res, 200);
    assert(
      data.results[0].merchant.toLowerCase() !== 'amazon',
      `"amazonian" should not match Amazon, got ${data.results[0].merchant}`
    );
  });

  await test('Partial-match merchants (Chipotle, Walgreens)', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: [
          'CHIPOTLE MEXICAN GRILL 0231',
          'WALGREENS #4821 PHOENIX',
        ],
      },
    });
    assertStatus(res, 200);
    assert(data.results[0].merchant.toLowerCase() === 'chipotle',  `Expected Chipotle, got ${data.results[0].merchant}`);
    assert(data.results[1].merchant.toLowerCase() === 'walgreens', `Expected Walgreens, got ${data.results[1].merchant}`);
    assert(data.results[0].category === 'food',   `Expected food, got ${data.results[0].category}`);
    assert(data.results[1].category === 'health', `Expected health, got ${data.results[1].category}`);
  });

  await test('Keyword fallback for unknown but recognisable merchant types', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: [
          'JOES COFFEE ROASTERS',
          'DOWNTOWN PHARMACY LLC',
        ],
      },
    });
    assertStatus(res, 200);
    assert(data.results[0].category === 'food',   `Coffee shop should map to food, got ${data.results[0].category}`);
    assert(data.results[1].category === 'health', `Pharmacy should map to health, got ${data.results[1].category}`);
  });

  await test('Mixed known and unknown merchants', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: [
          'WALMART SUPERCENTER',
          'XYZUNKNOWNMERCHANT99',
          'NETFLIX.COM',
          'RANDOM STORE 4821',
        ],
      },
    });
    assertStatus(res, 200);
    assert(data.results.length === 4, `Expected 4 results, got ${data.results.length}`);
    assert(data.results[0].merchant.toLowerCase() === 'walmart', `Expected Walmart, got ${data.results[0].merchant}`);
    assert(data.results[2].merchant.toLowerCase() === 'netflix', `Expected Netflix, got ${data.results[2].merchant}`);
    // Unknown entries should still have a merchant and category field
    assert(typeof data.results[1].merchant  === 'string', 'Unknown merchant should still have a merchant field');
    assert(typeof data.results[1].category  === 'string', 'Unknown merchant should still have a category field');
    assert(typeof data.results[1].confidence === 'number', 'Unknown merchant should still have confidence');
  });

  await test('Completely unknown merchant falls back gracefully', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: { transactions: ['XYZUNKNOWNMERCHANT123', 'RANDOM STORE NAME 9999'] },
    });
    assertStatus(res, 200);
    data.results.forEach((r, i) => assertResultShape(r, i));
    // Should not throw or return empty fields
    assert(data.results[0].merchant.length > 0, 'merchant must not be empty string');
    assert(data.results[0].category.length > 0, 'category must not be empty string');
  });

  await test('Confidence is higher for exact matches than uncategorized', async () => {
    const { res, data } = await call({
      key: TEST_KEY_ACTIVE,
      body: {
        transactions: ['NETFLIX', 'XYZUNKNOWNMERCHANT'],
      },
    });
    assertStatus(res, 200);
    const exactConf = data.results[0].confidence;
    const unknownConf = data.results[1].confidence;
    assert(
      exactConf > unknownConf,
      `Exact match (${exactConf}) should have higher confidence than uncategorized (${unknownConf})`
    );
  });
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main() {
  log('\n=== Transaction Categorization API — Integration Tests ===\n', colors.blue);
  log(`  Target: ${API_URL}`, colors.dim);
  log(`  Keys loaded from: .env.test\n`, colors.dim);

  await runPhase1();
  await runPhase2();
  await runPhase3();
  await runPhase4();
  await runPhase5();

  log('\n' + '─'.repeat(52), colors.blue);
  log(`\n  Passed: ${passCount}`, colors.green);
  if (failCount > 0) {
    log(`  Failed: ${failCount}`, colors.red);
    log('\nFailed tests:', colors.red);
    for (const f of failures) {
      log(`  ✗ ${f.name}`, colors.red);
      log(`    ${f.message}`, colors.dim);
    }
  } else {
    log(`  Failed: ${failCount}`, colors.green);
  }
  log(`  Total:  ${passCount + failCount}\n`, colors.blue);

  process.exit(failCount > 0 ? 1 : 0);
}

main().catch((err) => {
  log(`\nFatal: ${err.message}`, colors.red);
  process.exit(1);
});
